language: python
python:
  - 3.6
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script:
  coverage run --source=apiwrapper manage.py test
  python3 -m unittest
after_success:
  coveralls